title: Shagun Gupta
url: "http://shagungupta.net"
baseurl: ""

markdown: kramdown
ins_logo: "bits-logo.jpg"

tracking_id: UA-156492622-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: " .  "

sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "About"
 #   link: "/researcher"
 - name: "Github"
   link: "https://github.com/shagunn"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/shagunxgupta/"
 - name: "Email"
   link: "mailto:shagun.gupta@mail.utoronto.ca"


 # - name: "Contact"
 #   link: "contact"
